### ISSUE TITLE
Branching model

### ISSUE THREAD

**Issue by urbanhusky** [BudgetFirst/BudgetFirst#1]
What branching model should we employ - and how should we name the branches?
I'd like to keep the master branch as the "stable" branch, which should not be pushed to (only use pull requests).

We could create a "develop" branch and various milestone-branches whenever we need them.

**Comment by obstschale** [comment]
I personally like the git-flow approach. It is clean, simple, and easy to understand.

**Comment by urbanhusky** [comment]
That would be the most logical choice, I'll have to see what support github has for implementing that directly (i.e. no force push to master etc.)

**Comment by Skyfmmf** [comment]
To me git-flow always seemed to be a bit bloated. Other people with a similar thinkings described something I usually call "git-flow lite" 
A rather popular writing (with a provoking headline ;)) on this are these articles: 
 * http://endoflineblog.com/gitflow-considered-harmful
 * http://endoflineblog.com/follow-up-to-gitflow-considered-harmful

**Comment by urbanhusky** [comment]
My idea so far is to use the master as the stable branch, in which we only merge changes and hotfixes via pull requests. Develop is the branch where we'll push and merge all the current stuff into. Branching from develop are going to be other branches, that need to be isolated enough without disturbing the develop branch. I'm not sure if we'll have many such branches or just one or two at a time or if we can work on develop directly.

**Comment by Skyfmmf** [comment]
I would try to only do fast-forward merges from develop and (if necessary) hot-fixes on the master (Second link, second sub-heading).
 
Pull requests and the result of feature braches should be merged into development I think. Eventually there should be pull requests into a feature branch if it's a large feature with many developers working on it. If it's a smaller feature someone is working on alone, the feature branch should not be present in the main repository I think.

**Comment by Argent** [comment]
I would suggest the following branching model:
- `Master` contains only release version. When we want to build a new release we merge `Develop` into `Master`. Nobody commits to `Master`
- `Develop` contains the current development stage. Nobody commits to `Develop`. Merges into `Develop` always have to be done with a Pull Request.
- Development is done in feature branches. All commits are done in a separate branch. If you want to merge it to develop you have to create a PR and await approval before you are allowed to merge it.

I worked with this model for a while now and it works really well

**Comment by urbanhusky** [comment]
Hm, that would be a good model. Should the base branch be develop then?

**Comment by Skyfmmf** [comment]
This model sounds fine for me to.

**Comment by chisaipete** [comment]
I've used a similar model for a while as well, I approve. :)

**Comment by damiansilbergleithcunniff** [comment]
I have used that model in the past.  Generally develop is the default and master is locked down.  Only approved users can modify master.  Merges from develop to master happen on a release branch and are require an approved pull request.

**Comment by dmackerman** [comment]
@Argent's model is pretty standard for many projects, and familiar.

**Comment by urbanhusky** [comment]
Okay, we'll use that model then :)

**Comment by rasliche** [comment]
Should this issue be closed then? (I strongly agree with the decision made)
