### ISSUE TITLE
GitHub page not accessible 

### ISSUE THREAD

**Issue by Skyfmmf** [BudgetFirst/BudgetFirst#3]
The website under https://budgetfirst.github.io/ is currently not available. 

The documentation for GitHub pages (https://help.github.com/articles/creating-pages-with-the-automatic-generator/) says, the page must be in an own repository called ``<organisation-/username>.github.io`` (in our case budgetfirst.github.io) and not in a branch in another repository.

**Comment by urbanhusky** [comment]
I used the page editor to create it, which then created the branch.
The site is online at http://budgetfirst.github.io/BudgetFirst/

**Comment by Skyfmmf** [comment]
Ok, the project page under https://budgetfirst.github.io/BudgetFirst/ works now. 

But I think it would be a better idea to use the organization GitHub page (butgetfirst.github.io) as it has a shorter URL and you do not mix up the code of the software and the one of the website in one repository.

To archive this you would have to create a new repository for the organization wit the name ``butgetfirst.github.io``, add an gh-pages branch and then add the content that you already created. Or you could just use the page editor inside this new repository.

**Comment by urbanhusky** [comment]
Okay, thank you - I've set up the page for the organization. I'm not entirely sure how to redirect best, so I've replaced the index.html on the old site with a redirect via meta refresh (and hopefully, as fallback, javascript).

**Comment by lukaswelte** [comment]
Seems legit.
I think this issue can be closed now.
