### ISSUE TITLE
Support for multiple currencies

### ISSUE THREAD

**Issue by urbanhusky** [BudgetFirst/BudgetFirst#33]
This question came up on reddit so I'd like to address it here.
Is there demand to support multiple currencies and how should this support work?

I doubt that it is possible to include multiple currencies in a single budget, but we might be able to support off-budget accounts in foreign currencies (a transfer to such an account would be a special case).

Another option would be to support multiple budgets and perhaps link accounts from one budget to another. You might have one account on budget X and another on budget Y. This would allow you to budget with multiple currencies.

Why can't we just put multiple currencies into a budget? Because of exchange rate fluctuations. The money you add to your account is worth different amounts of your core budgeting currency depending on when you have it as income or spend it. 
Example: I transferred 100€ to cash in CHF. This gave me 120 CHF. Both accounts are on budget so I still technically have 100€ worth to spend. I then spend 100 CHF which is now worth 90€ instead of 83€ (exchange rate went from 1:1.20 to 1:1.10) - so I can't really use the current exchange rate but would have to use the exchange rate of when I received the 120 CHF... 
...this gets even more fun if I want to spend 1000 CHF and put aside 100 CHF each month, each with a different exchange rate... How do you budget for that?

**Comment by dotnick1** [comment]
It's not a feature I would use because I'm in the US.  What do people in the EU do when they travel to countries that don't use the euro?  Do they use seperate bank accounts for different currency?  

Would an option in a category definition that only allows transactions against a selected on-budget account work?  It would be like a nested budget.  

I've seen this question raised before, but I never understood the workflow.  The closest thing like this that I do is that all business expenses go towards my credit card and nothing else.  So the budget category and credit card balance are always the same, but its not forced by ynab so I could screw it up.  If it was forced, a different currency could be used and the conversion rate wouldn't matter except for transfers between accounts.  Prompt every time for rate?

That's all I have, from a person this won't affect.

**Comment by urbanhusky** [comment]
Personally, I have had this issue where I have both EUR and CHF - because I have to pay for public transport or the occasional overpriced thing in CHF. In the past I had an off-budget account for my CHF cash and budgeted the entire amount I transferred to it upfront. Obviously, that's not ideal.

So yes, I'm carrying both EUR and CHF in cash. I don't have separate bank accounts but that might also be something that some people do (for example: it is not uncommon for people in my region to work in Liechtenstein or Switzerland. They get paid in CHF and some keep a bank account in CHF so that they can transfer the money to their EUR bank account whenever the exchange rate is favourable - or withdraw CHF directly; It's rather expensive to get cash in a foreign currency...)

I couldn't use the same budget because of the exchange rate issues so the only option left seems to allow for multiple budgets (and assigning accounts or subaccounts to a specific budget - or none).

**Comment by Ps0ke** [comment]
I would like to have multiple currencies, too, since I'm going to study abroad and will have multiple bank accounts. A foreign for paying rent and cash withdrawal etc, but most of my assets still on my native account(s).
But this would probably only affect off budget accounts and transfers at a fixed point in time with well defined exchange rate.
How does The Other Budget Management Software™ do it?

**Comment by urbanhusky** [comment]
Off-budget accounts in other currencies should very well be something that we can support. If there is need for anything more complex, please let us know :)

**Comment by ruipgpinheiro** [comment]
I'd actually suggest support on-budget accounts with different currencies, as that's my main complaint about a specific other budget management software (no support for multiple currencies).

The main idea here is to basically support multiple budgets in different currencies seamlessly. There's a few ways this could be done:

1. Have separate budgets per currency. When recording an expense, your chosen account's currency restricts which budget(s) you can use - you're only allowed to register an expense on a budget with the same currency.
2. Each category can have a currency. When recording an expense, depending on your chosen account's currency, you are restricted to categories with the same currency.
3. Each category has a trio of "Budgeted", "Outflows" and "Balance" for each active currency. So, I can budget in £ for one category, € for another, and both for a third.

When doing transfers between accounts with different currencies, require the user to enter Outflow and Inflow (and don't require them to be the same).

Something like this could work perfectly!

**Comment by urbanhusky** [comment]
I think the best option here would be to support multiple budgets in the same file/sync. Each account would be associated with a single budget (or none). Otherwise it might get difficult to allocate income over all budgets etc.

Generally, that is something that could be done but I personally don't see it as a must-have feature for our first big release since most people won't need it right away. That only means that it will be a little longer before we have this feature (e.g. could be in v1.2 or v2.0)

**Comment by ruipgpinheiro** [comment]
My suggestion was to treat different-currency budgets as completely separate and independent, yes, but additionally to the separate "per-budget view", have a "unified view" where categories from multiple budgets are shown together. This would be easy to organize as long as each budget has a different currency.

**Comment by urbanhusky** [comment]
I'd be careful with the wording of _completely separate and independent_. That suggests that you could just as well use separate budgets (as in: separate files). 

I'm not sure how useful a view over all budgets would be, considering how many budgets and categories there might be. I also doubt that you could budget efficiently in such a view - after all, we'd need to track the income, outgoing and budgeted amount per month and budget...

Anyway, my proposal so far is:
Allow for multiple budgets (whose currency does not need to match to other budgets) in a file. An account can be associated with one of these budgets - or none. 
That also means that whenever you enter a transaction, it's automatically associated with the corresponding budget.

However, this might make reporting later a bit more difficult because each category in each budget is separate - but maybe that's even a good thing. Currently I see very little use for 99% of my categories if I would have another foreign currency budget. I certainly would not pay my rent etc. with it.

**Comment by urbanhusky** [comment]
Closing this. We'll support multiple budgets. Each budget can have any currency.
Accounts will belong to a single budget ("off budget" is just another special budget).

This means that any transaction is always tied to the account and thus the corresponding budget.
