### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by urbanhusky** [BudgetFirst/BudgetFirst#4]
I'm not sure what the default branch should be. `master` or `develop`? 
Should this be even changed now? Right now it's `master`

**Comment by chisaipete** [comment]
Perhaps leave it as master, no need to make a change for change's sake.

**Comment by Skyfmmf** [comment]
I think we should leave it on master for now. If we see any problems with that later on, we can change it at any time.

**Comment by Argent** [comment]
Since `master` will contain the release version, I think `master` should be the default

**Comment by urbanhusky** [comment]
Okay, I'll leave it as master.
