### ISSUE TITLE
Invitations to Slack and Taiga

### ISSUE THREAD

**Issue by urbanhusky** [BudgetFirst/BudgetFirst#5]
Get in touch with me if you want to contribute to the project. I need an email address to invite you to Slack and Taiga for planning, those projects don't seem to do join requests.

Possible ways of contacting me:

Post on the google group (beware: it's publicly accessible so your email address is visible): https://groups.google.com/forum/#!forum/budget-first
Send a private message on twitter to `@budgetfirst`
Find some other means of contacting me (currently I can't think of any, sorry)

**Comment by obstschale** [comment]
For Slack I recommend using Slackin. A simple tool. It allows users to send a invitation mail automatically to themselves. http://rauchg.com/slackin/

**Comment by urbanhusky** [comment]
Currently, all we have is github pages, would that be compatible with it?

**Comment by obstschale** [comment]
Nope. You need to run it on your own server.

**Comment by optikfluffel** [comment]
But I guess running on a free Heroku instance would be fine. They even have one of this nice 1-click-deploy buttons [in their README](https://github.com/rauchg/slackin/blob/master/Readme.md#heroku).

**Comment by urbanhusky** [comment]
I'll have a look at Heroku then, thanks

**Comment by urbanhusky** [comment]
Invitations to slack can now be requested most of the day: https://budgetfirst.herokuapp.com/

**Comment by urbanhusky** [comment]
We're not really using Taiga much at the moment, there isn't that much to plan. Also, it is very limited in how it can be used (not wiki history etc.)
