### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by urbanhusky** [BudgetFirst/BudgetFirst#9]
Hi everyone,

it is looking more and more likely that we will switch development to Xamarin. I'm currently in the progress of building the framework to support the application - on a separate branch. Feel free to have a look into it and provide feedback.

Yes, this means dropping Linux support. However, since we're opensource, you're still free to port it.

We'll have to write at least two, if not four, different presentations: WPF (Windows Vista?, 7 etc.), Xamarin.Forms (Mac/Win10), Xamarin.iOS and Xamarin.Android. We might be able to reuse most of the logic, even presentation-specific stuff by introducing a viewmodel that supports actions (i.e. you'd just have to bind the "Add transaction" button to the corresponding action on the model).

We might drop the development branch because of the large size - all the node modules add up to quite a lot. I wouldn't want everyone to have to deal with such things. If it comes so far, we'll just add a new development branch with a different name and will try to delete the old development branch.

Progress will still be slow from my side, because I can only work a few hours per week on the side, but we're already progressing so much faster than in the past months. 

What are your thoughts on this?

**Comment by MI3Guy** [comment]
Linux user here.

You might want to consider using Eto.Forms for the desktop. It supports MVVM and supports WPF, Cocoa, and Gtk#. It does have its quirks though.

Failing that, I could try to get it working on Gtk# depending on how much of a time investment it becomes.

**Comment by urbanhusky** [comment]
How would the code run on Linux then? The core is written in .NET portable class libraries.

**Comment by MI3Guy** [comment]
Sorry, I don't understand. Why wouldn't it work? PCLs run on mono.

**Comment by urbanhusky** [comment]
I'm not familiar with Mono, hence my asking. Am I correctly interpreting that Mono can run .NET PCLs?

**Comment by MI3Guy** [comment]
I just created a project in MonoDevelop to demonstrate it. Besides that, my understanding is that a PCL is really just the same as a normal library except the compiler restricts the available APIs.

**Comment by urbanhusky** [comment]
Could you test if the `xamarin-init` branch builds and can be referenced for you with Mono? If our .NET PCL's run fine on Mono, then we might be able to offer Linux support too.
I'm not sure if I'd build the entire UI with Eto, I'd rather stick to platform-specific UIs (especially iOS and Android). I'm not a huge fan of the declarative style and potential restrictions. But Eto/GTK# might offer a path into Linux support.

**Comment by MI3Guy** [comment]
I added a basic Gtk# project. If we want platform-specific UIs then using Gtk# directly probably makes the most sense.

https://github.com/MI3Guy/BudgetFirst/tree/xamarin-init

A few notes:

1. MonoDevelop apparently uses an older ToolsVersion in the csproj files than VS2015. Sorry for the deltas.
2. I can't load either the WPF or VS unit test project. No surprises there. Besides that everything builds. I added an NUnit project. I would recommend switching to an open source framework line NUnit or XUnit.
3. MonoDevelop's current NUnit runner doesn't support NUnit 3. This was apparently implemented, but hasn't been pushed out to the Xamarin PPA. I added the package for the command line runner in the meantime.
4. Gtk# can be used from Windows as well so the Windows developers can help with that as well without messing with mono or linux aside from installing the Gtk# runtime.

**Comment by urbanhusky** [comment]
Unit test framework: we'll have to see which one we'll use. True, MSTest might not be the best choice for multiplatform - but I really like the integration into Visual Studio.

Anyway, Linux/Gtk# will be one of the last things to add to the project. My focus is on getting the application working under WPF and Xamarin.Forms.

**Comment by bnSonic** [comment]
Short word to Xamarin.Forms:

We've tried Forms in our company to develop one GUI that could work for iOS
and Android.
Long story short: We lost about 2 months and started all over with native
GUI for each platform

Problem with Xamarin.Forms: You will always miss some properties,
functions, callbacks. Putting the search-field inside a list-view wasn't
possible (maybe it is now - Xamarin is working on Forms), setting Pins on a
Map wasn't possible (at least not that easy as with the native control) and
so on

I'm not sure how this will work for OS-X / Windows ...

For example i'm not sure if there a i good Grid-Component available or
Edit-Fields doing some "tricks" for easy entering Dates and so on... Maybe
you cannot use any third-party-control because most of them won't base on
Xamarin.Forms :)

Just to give you an idea... The code for the logic and data-storing should
always be seperated from the GUI-code - so maybe it's not the worst idea to
consider different GUI for each plattform (native) instead of using
Xamarin.Forms.

urbanhusky <notifications@github.com> schrieb am Mi., 20. Apr. 2016 um
07:55 Uhr:

**Comment by urbanhusky** [comment]
The main reason for Xamarin.Forms would be the support of OSX. Windows will be primarily supported through WPF.

The entire logic will be separated, even the viewmodels will get their own PCL.

**Comment by MI3Guy** [comment]
Does Xamarin Forms actually support Mac? Even if it does, I would think it would make more sense to use the MonoMac (or maybe Xamarin.Mac) library.

**Comment by urbanhusky** [comment]
Well, Xamarin.Forms is something that I could work on and test (as UWP). Anything else would require the purchase of a Mac. I also like the idea of getting fully featured iOS and Android builds with it, for use on larger devices - but I don't have any experience with Xamarin.Forms so I can't really say what is possible and what isn't at this point.
My initial focus is on getting a WPF application running, so that we can evolve the user interface and work on the domain.

**Comment by strand** [comment]
Hey, I came here from searching for open source envelope budget, and as a MacOS/Linux user, I am disappointed there will not be a Linux version. I have used YNAB in the past, and want to be able to have a Linux client…

**Comment by urbanhusky** [comment]
A Linux version is likely still going to be developed with GTK#. We have multiple different platforms where we have to develop the user interface separately for, so there might be a delay in implementation speed unless other people pick up the GTK# integration. Personally, I'll focus on the WPF application first as this is the platform I can best develop and test on/for. That does not mean that I only want to release a WPF based application - far from it. I just want to get to a more feature-complete point before personally worrying about other platforms.
This is also because I'd like to keep a uniform UX across platforms, so we'll need some template for all.

**Comment by urbanhusky** [comment]
We're definitely going with Xamarin now.
